### ISSUE TITLE
Drupal Console - not recognising Drupal site directory

### ISSUE THREAD

**Issue by stephenpurkiss** [hussainweb/drupal-composer-helper#9]
This is awesome, thank you!

I'm having troubles with Drupal Console, when I type 'drupal list' in the `web` directory it says:

`[WARNING] In order to list all of the available commands, you should run this against a drupal root directory.`

I did a `composer require drupal/console:~1.0` but didn't need to as see it's already there so wondering what I've done wrong or whether there's something I've missed out!

Thanks again for your wonderful work!

**Comment by hussainweb** [comment]
Thanks for reporting this. I debugged a bit and found out why this happens. The problem is that webflo/drupal-finder relies on `installer-paths` to find out where Drupal is installed.

As of right now, the only workaround I can think of is having the installer-paths in your composer.json with just one entry:
```
{
    ...
    "extra": {
        "drupal-composer-helper": {
            "web-prefix": "web"
        },
        "installer-paths": {
            "web/core": ["type:drupal-core"]
        }
    },
    ...
}
```

This kind of defeats the point of using this plugin slightly and I will look out for better workarounds. I am also going to submit fixes for webflo/drupal-finder but it might be a while before it gets accepted and updated everywhere. Meanwhile, this should work.

**Comment by stephenpurkiss** [comment]
Awesome thanks, that works a treat!

**Comment by webflo** [comment]
Hi, i am trying to understand how drupal-composer-helper does its magic. It adds the installer path on runtime. Is this correct?

**Comment by hussainweb** [comment]
That's right. It just uses the `web-prefix` as a base and sets everything else with sensible defaults. Each of those can be overridden, of course.

**Comment by hussainweb** [comment]
Going to track this now in https://github.com/webflo/drupal-finder/pull/49
